### ISSUE TITLE
Update the list of machines.

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#108]
Some stuff is missing for some machines. Some machines need an image for the machine list. Some need an SOP created and linked. Some need a maintenance log created and linked.

There are some gotcha's to remember. The images need to be reduced to a _reasonable_ size (500 px on the shortest edge). For machines where there is no SOP yet, the placeholder SOP must be created in the appropriate location _and also linked_ in _data/machines.yml. The "title" in the YAML header of the SOP must exactly match the "name" in _data/machines.yml in order for the maintenance log to be automatically linked in the SOP. It's totally fine for the content of the placeholder SOPs to be "an SOP hasn't been written yet". Maintenance logs must be created in the [LOG BOOKS](https://drive.google.com/open?id=1iau9183JUifl_fH4g7AXuHAGlamhXRnK) folder the Google Drive. 

- LPKF S63
  - [X] image
  - [x] SOP
  - [X] uses the "sop" layout
  - [X] maintenance log
- Solder Oven
  - [X] uses the "sop" layout
  - [X] maintenance log
- pick and place
  - [X] image
  - [X] SOP
  - [X] uses the "sop" layout
  - [X] maintenance log
- test and measurement
  - [C] uses the "sop" layout  
    not actually appropriate here
  - [C] maintenance log  
    not actually appropriate here
- mojo
  - [X] uses the "sop" layout
  - [X] maintenance log
- shining 3D scanner
  - [X] uses the "sop" layout
  - [X] maintenance log
- mill
  - [X] uses the "sop" layout
  - [X] maintenance log
- lathe
  - [X] uses the "sop" layout
  - [X] maintenance log
- drill press
  - [X] uses the "sop" layout
  - [X] maintenance log
- thermocutter
  - [X] uses the "sop" layout
  - [X] maintenance log
- wazer
  - [X] image
  - [x] SOP
  - [X] uses the "sop" layout
- Full Spectrum Pro
  - [X] uses the "sop" layout
  - [X] maintenance log
- Full Spectrum... unknown model
  - [x] image
  - [x] SOP
  - [x] uses the "sop" layout

**Comment by jejor** [comment]
What happened to the K40 on the main lists? Are we getting rid of it?

**Comment by Joedang** [comment]
Searching through `git log --graph -p --full-diff machines.yml`, it looks like it got commented out on 67ee78ceb80 and accidentally (?) deleted on e0dee464929f. AFAIK, we're still using it to make stencils. @clarkatron and @tiffanishilts , do y'all have more information?

**Comment by Joedang** [comment]
@tiffanishilts says it was removed accidentally. It's re-added in 58b0a91.

**Comment by Joedang** [comment]
The Pick-and-place got its skeleton documents last week, and the testing stuff isn't really relevant. (Each piece of equipment gets its own SOP.)
