### ISSUE TITLE
GitHub mobile test

### ISSUE THREAD

**Issue by eivory** [psu-epl/psu-epl.github.com#117]
Let's test issues on mobile. I'm able to submit a new issue via iOS app.

**Comment by eivory** [comment]
And I can comment. Can you?

**Comment by eivory** [comment]
And it appears to allow me to post photos and close issues. ![image](https://github.com/psu-epl/psu-epl.github.com/assets/18200562/37a7b71a-3a25-41b5-9bdb-d1cd9798c8b9)

**Comment by Benjamin-C** [comment]
I can comment
- from Github Android app

**Comment by Benjamin-C** [comment]
![Screenshot_20231209-125642_GitHub.png](https://github.com/psu-epl/psu-epl.github.com/assets/23143794/e920d684-29a0-40ee-9fe0-6c9bc7d50fd5)

**Comment by mahnazghanbar197** [comment]
> I can comment
> - from Github Android app

**Comment by mahnazghanbar197** [comment]
> > I can comment
> > - from Github Android app
> 
> 

Yes xiaomi note 12 bag

**Comment by mahnazghanbar197** [comment]
> میتونم نظر بدم
> 
> * از برنامه اندروید Github

Yes

**Comment by mahnazghanbar197** [comment]
> > > میتونم نظر بدم
> > > 
> > > * از برنامه اندروید Github
> 
> بله کیف نوت 12 شیائومی
