### ISSUE TITLE
QD 1390 (Big) Laser Cutter Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#12]
- [x] Clean up the existing SOP according to the style guide.
- [x] Review/revise the existing SOP.
- [x] Add any missing documentation (manufacturer manual, et cetera).

**Comment by MechBertrand** [comment]
The manual linked by the current SOP is not for this laser cuttor but for the full spectrum.

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> 1.  Include sections on exporting dxf from inkscape and blender
> 
> 1.  Move dxf instructions to its own document, add link?
> 
> 3.  Pictures seem pretty fuzzy. Not mission critical, but could help with overall feel
> 
> 4.  Picture of red circle around key should include circular arrow showing which way to turn key
> 
> 5.  Picture of water chiller should include red arrow indicating the toggle switch
> 
> 6.  Material tests need to be updated, AFAIK they are from before we renovated the laser, and are not accurate.
> 
> 7.  Change title "Changing Cut Setting in RDWorks" to "Changing Cut Setting in RDWorks -- Using Layers"
> 
> 8.  Change `different "colors" to identify different layers on your piece.` to `different "colors," also known as "Layers" to identify different layers on your piece.`
> 
> 9.  "Using different cut settings in your job (i.e. cutting or etching, etc.): <>"  is "<>" intentional here?
> 
> 10. Add a paragraph to the beginning of the Layers / cut settings section explaining what layers actually are, eg:
> 
> 1.  "RDWorks controls all cut settings using what it calls Layers. Essentially, every line in your cut can have a layer assigned to it, and when RDWorks commands the laser cutter, it will use the settings for that layer on that line."
> 
> 2.  "Layers in RDWorks are pre-assigned colors. To apply settings to your geometry, you must first assign it to a new layer. To do this, select the geometry and click one of the color boxes at the bottom of the screen"
> 
> 3.  "The new color will now appear in the layers table in the upper right of the screen, where you can edit it"
> 
> 4.  etc, etc
> 
> 12. Add check for air coming out of laser head when air turned on (put hand in front of the tube, you should feel the compressed air, etc)

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> Laser QD-1390 sop revisions
> 
> *Let 'L' represent a line under step
> 
> General Notes:
> 
> L1: add definition of rastering?
> 
> Safety:
> 
> L1: where is eye protection located? ANS: big red tool box
> 
> L3: emphasis on fire extinguisher, bold?
> 
> Prepping the Laser:
> 
> L1-L3: fix bullet points from all 1's to uniform per document
> 
> Preparing your Job
> 
> L3/L4: fix bullet points from all 1's to uniform per document
> 
> *it says there are issues that can happen but there is no picture of a successful import. I think an image would be useful here.  
> 
> L4.1: add 'to' in missing spot.. You will have to manually edit your job
> 
> Changing Cut Settings in RDWorks:
> 
> Again the bullet points are all 1's and weird numbering everywhere :|
> 
> Aligning and Testing:
> 
> 1's
> 
> Final Prep:
> 
> L1: air filter location?? Says to left of machine but I see it not, replaced with new dealio?
> 
> L2: air compressor is not green, update pic with new compressor

**Comment by Joedang** [comment]
Let's see how well the whole comment-via-email thing works...

The "1s" problem that's happening throughout the document is from the blank
lines between the items. In Markdown,  a blank line is interpreted as a
paragraph break. So, if you have a blank line between every item of a list,
you're actually starting a new list with each item. Hence, each item is the
first item.

We will also want to shrink some of those images. Some of them appear to be
in their original resolution, and take a while to load on mobile. This
script is convenient for doing *img2small *.jpg*, if you don't mind
installing a Python library:
https://github.com/Joedang/dotfiles/blob/master/bin/img2small

This is more of a note to myself, but it "would be nice" to have numbered
sub-items use, say, lower-case Roman numerals rather than Arabic digits,
just to differentiate the two. I think this would require mucking with the
LESS, so it's probably not worth it.

**Comment by MechBertrand** [comment]
Could using html be a decent work-around for image size?
<img src="path/file" width="XX%" >  (something like that anyways)
Does Jekyll like this? It's worked in all my endeavors with markdown
anyways.

Note: XX% is of page/paragraph width.

**Comment by Joedang** [comment]
I'm pretty sure that changing the image size in the HTML would not help. It
just tells the browser to display the image at a certain size. The browser
still requests the same image from the server. So, if you had a 1000x1000
image in the repo, but specified it as <img src="kitten.jpg" width="500px">,
it would still transmit the 1000x1000 file and display it as 500x500
on-screen. The slow step is (I'm pretty sure) the transmission, not the
displaying.

**Comment by faberc** [comment]
Confirmed that this issue is still open.

**Comment by jejor** [comment]
*Copied from Issue #50*
ir4 wrote:
"Went through the SOP and think that we should add a range for Power and Speed settings in part 6 of the Changing Cut Settings in RD Works paragraph. Or we can add a picture since we already have example pictures for cut settings why not one for scanning.I also think we could add a picture of the new air compressor since the on/off switch is on the top now and a range for what both pressure gauges should readAdding pictures showing the chiller, air filter in off or on position. Since we already have it for the laser I think that would help other new users as well."
--
Issue #50 closed.

**Comment by jvinh890** [comment]
> The manual linked by the current SOP is not for this laser cuttor but for the full spectrum.

There is no manual for this laser cutter, the company that makes them seems to have died off somewhere along the line.
