### ISSUE TITLE
Full Spectrum Laser Cutter Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#13]
- [x] Clean up the existing SOP according to the style guide.
- [x] Review/revise the existing SOP.
- [x] Add any missing documentation (manufacturer manual, et cetera).

**Comment by Flynnn** [comment]
I know next to nothing about this laser, but I'd love to learn about it. This is another one of those taht someone else is welcome to take over if I don't get to it quickly.

**Comment by faberc** [comment]
Confirmed issue still exists.
