### ISSUE TITLE
Drill Press Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#15]
- [ ] Clean up the existing SOP according to the style guide.
- [ ] Review/revise the existing SOP.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by faberc** [comment]
Confirmed issue still exists.

**Comment by faberc** [comment]
Started a new SOP on Google Docs (https://docs.google.com/document/d/16IWrEWu0RaItxTsq3b8yVzDhWtIEp5NGPIC3dYHJr-c/edit?usp=sharing). 

Still needs to be finished.

**Comment by jejor** [comment]
done.
