### ISSUE TITLE
Mini Mill Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#17]
- [ ] Clean up the existing SOP according to the style guide.
- [ ] Merge extra documents into the SOP, if applicable. 
- [ ] Review/revise the existing SOP.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by haneefmubarak** [comment]
From the doc, per Braulio (migrating):

> [sic]

**Comment by faberc** [comment]
Unsure if issue still exists. @haneefmubarak Has this SOP been fixed?

**Comment by Flynnn** [comment]
@faberc SOP has not been fixed. Here are issues from @haneefmubarak 

Could use more pictures in "Setup" and "Changing Tools".

Needs a much better explanation of climb and conventional milling, along with a discussion on when to do what; when Jordan trained me, I distinctly remember him teaching me that sometimes you do need/want to climb mill, and how to do that in a not-bad way.

The "Milling" section needs vast expansion to actually explain things in a remotely useful manner.

Lots of TODOs sprinkled around. Fix them.

Haneef: "I would not have a clue what is going on after reading this as a complete newbie."

**Comment by jejor** [comment]
@Joedang does this issue still exist?
