### ISSUE TITLE
FormLabs 2 Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#18]
- [x] Clean up the existing SOP according to the style guide.
- [x] Merge extra documents into the SOP, if applicable. 
- [x] Review/revise the existing SOP.
- [x] Add any missing documentation (manufacturer manual, et cetera).

**Comment by faberc** [comment]
Confirmed issue still exists.

**Comment by faberc** [comment]
Some code is appearing on the pages that shouldn't. We should probably get rid of one of the pages.
