### ISSUE TITLE
Mojo 3D Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#19]
- [x] Clean up the existing SOP according to the style guide.
- [ ] Review/revise the existing SOP.
- [ ] Add any missing documentation (manufacturer manual, et cetera).
- [x] Mojo SOP needs pictures added.

**Comment by faberc** [comment]
Confirmed issue still exists.

**Comment by jejor** [comment]
Looks like some work was done on this. Does this issue still exist? @Joedang
