### ISSUE TITLE
Ultimaker 2 Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#21]
- [ ] Clean up the existing SOP according to the style guide.
- [ ] Merge extra documents into the SOP, if applicable. 
- [ ] Review/revise the existing SOP.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by faberc** [comment]
SOP definitely needs some cleanup. Confirmed issue exists.

**Comment by jejor** [comment]
- [ ] Update 3D-Printing-Checklist with new policies. (ex. paying before printing)

**Comment by Flynnn** [comment]
Here are some general tips that were in the 3D-Printing checklist that should be added to the Ultimaker SOPs. Consider merging SOPs for both Ultimer 2 and 3?

    Part is oriented with the largest flat surface down

    Problem surfaces (highlighted red) have support material

    Support material is checked in the print settings

    Gcode preview (eye button -> Layers) looks reasonable

    Supports appear in the gcode preview

    Part sizes match the specified bounding box.

    Add the name and location of the gcode to the queue

    Add the cost and print time to the queue

    Gcode looks reasonable in Cura (see previous section)

    Build plate has a thin layer of glue

    Spool has enough fillament

    There are no jobs ahead of this print in the queue

    Make a sticky note for the print
        Name of the person ordering the print
        Name of the gcode file
        Price of the print
        Stick in on the printer

    Mark it as "printing" in the queue

**Comment by jejor** [comment]
issue merged to #73
