### ISSUE TITLE
Ultimaker 3 Extended Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#22]
- [ ] Create an SOP conformant to the style guide.
- [ ] Merge extra documents into the SOP, if applicable. 
- [ ] Review/revise the existing SOP and documentation.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> Ultimaker 3 Extended Setup
> ==========================
> 
> Box contents:
> -------------
> 
> -   PLA silver metallic filament (1x)
> 
> -   PVA "natural" filament (1x)
> 
> -   Power cable (1x)
> 
> -   Test print demonstrating dual extrusion
> 
> -   Ultimaker 3 extended (mostly assembled)
> 
> -   Accessory box containing:
> 
> -   Glass build plate (1x)
> 
> -   Ultimaker "calibration card"
> 
> -   24V Power supply
> 
> -   Glue stick (1x)
> 
> -   Tube of "Magnalube" (1x)
> 
> -   #2 Precision hex head screwdriver (1x)
> 
> -   Print core AA 0.4 (2x)
> 
> -   Print core BB 0.4 (1x)
> 
> -   Spool support and filament guide assembly (1x)
> 
> -   RJ45 Network patch cord (3m)
> 
> -   Unilube machine oil (1x)
> 
> -   Verbatim 16GB USB flash drive (1x)
> 
> Assembly
> --------
> 
> -   Gently place the printer on its side and examine case for any shipping damage or obvious flaws that would necessitate returning it.
> 
> -   Insert the spool holder into the back of the machine and gently rotate into place until the locking tabs snap into place.
> 
> -   Route the NFC cable through the labeled slot in the back of the case and plug into the labeled port on the control board.
> 
> -   Install the accompanying cable cover over the NFC cable. Align top of the cover first to the spool holder then gently snap the locking tabs into place.
> 
> -   Return the machine to the upright position and remove the packing material from around the build plate area.
> 
> -   Open the front build plate locking tabs by rotating\
>     ![](https://lh5.googleusercontent.com/bMpVTlJjlUfeVeYHjZEDWqCpsyo0CPOw2qIARQ6Xo3ky9ZTG6qAQ7KWEqWvXXeFHJiVPSqNAZSCyANUNf4T-CWwdVOFcLehn12QMTpdgvRfqGTTiOguxZrJvHCq4bG-FXwMMlet2){width="0.23958333333333334in"height="0.125in"}\
>     away from the center of the build area.
> 
> -   Remove any fingerprints from the build plate glass using a dry microfiber cloth.
> 
> -   Insert build plate glass into the back locking tabs gently pressing on the front edge of the glass to align the glass with the edges of the build plate heater.
> 
> -   Rotate the front locking tabs back into their original positions.
> 
> -   Using a pair of side cutters remove the zip ties holding theprinthead in place.
> 
> -   Plug the power supply into the back of the machine flatside downwards.
> 
> -   IT'S ALIVE!!!!!1!
> 
> Uploading Files in the Queue
> ----------------------------
> 
> -   Open the File Explorer
> 
> -   Navigate to Desktop\Queue 2018-2019
> 
> -   Create a folder with your first and last names. This folder will house all of you files for your projects.
> 
> -   Copy your .stl files in to the folder you created
> 
> Adding your Job to the Queue
> 
> -   Open Google Chrome to the 3D Printer Queue from the favorites tab.
> 
> -   Navigate to the next available line. This is where you will put the relevant information for your job. Please do not edit any other rows that do not belong to you.
> 
> -   Name: This should match the name of your file in the Queue
> 
> -   Email: This should be your PSU email or best way to contact.
> 
> -   Date input: This will likely be today's date
> 
> -   STL Filename: This should be the names of the files you wish to print in this job
> 
> -   Gcode Filename: This should be the
> 
> -   Location: This should be where your folder is
> 
> -   Cost: This should be the cost of to complete your job
> 
> -   Time: This should be the time it takes to complete your job
> 
> -   User Requests
> 
> -   Appearance
> 
> -   Bounding Box or Scale
> 
> -   Color/Material: This is if you have a special color request. If left blank then we will print with whatever color is on the spool
> 
> -   Printer: This is which printer you would like your job completed on
> 
> -   Status: This is to be edited by managers only
> 
> -   Date Picked Up: This is to be edited by managers only
> 
> -   Paid: This is to be edited by managers only
> 
> Using the Ultimaker 3 Extended
> ------------------------------
> 
> -   The printer will guide you through the initial setup process.Controls are very similar to the Ultimaker 2
> 
> -   Insert instructions on how to work cura
> 
> -   Open up Cura from the Desktop
> 
> -   Select New Project
> 
> -   Select the printer you plan to use: Ultimaker 3 Extended or Ultimaker 2
> 
> -   Select Open Files, typically .stl files
> 
> -   Use the Move, Rotate, or Rescale tool to get your prints to be the right size and orientation to fit on the build plate.
> 
> -   Keep in mind that jobs are printed layer by layer from the bottom up. Thus hollow items with an opening should have the opening up. For explain a bowl would be oriented face up rather than face down.
> 
> -   Setting to tweak only if you know what you are doing
> 
> -   Infill Density:
> 
> -   Generate Support:
> 
> -   Build Plate Adhesion Type:
> 
> -   Once you believe your build is ready then click Prepare. This will generate goodness :)
> 
> Inserting the printer cores.
> 
> -   Gently press down on the front facing fan housing to open the printer core housing.
> 
> -   Insert the printer core by squeezing together the front plastic tabs and sliding the printer core into the desired slot.Firmly press the core into place until you hear a small click. The machine will auto detect the printer core being used.
> 
> -   Add picture here of the front facing fan, with arrows pointing to the plastic tabs that you need to squeeze
> 
> Loading the print material.
> 
> -   Load the material for print core #2 first.
> 
> -   Follow a similar material loading procedure to the Ultimaker 2
> 
> -   Load the spool for print core #1 and attach the guide arm to the end of the spool holder
> 
> -   Insert picture of someone doing this step, specifically with the 'guide arm''
> 
> -   The machine will guide you through the process.
> 
> Leveling the build plate
> 
> -   System > Build plate > Manual Leveling
> 
> -   Follow directions on the machine to level the build plate and set the Z-offset
> 
> -   This is not nearly thorough enough. What is the Z-offset?
> 
> Notes on prepping for print?
> 
> -   Like glueing the base plate, etc.

**Comment by faberc** [comment]
Not really a standard operating procedure. This is a setup guide. Not a general operating guide. An SOP needs to be written. Probably with tips on how to fix common issues.

**Comment by brandr2** [comment]
I started working on this SOP today, since it's incomplete I put it on the manager's drive under machines & equipment. Let me know if I need to move it.

**Comment by jejor** [comment]
[] Update 3D-Printing-Checklist with new policies. (ex. paying before printing)

**Comment by Flynnn** [comment]
Here are some general tips that were in the 3D-Printing checklist that should be added to the Ultimaker SOPs. Consider merging SOPs for both Ultimer 2 and 3?

- Part is oriented with the largest flat surface down
- Problem surfaces (highlighted red) have support material
- Support material is checked in the print settings
- Gcode preview (eye button -> Layers) looks reasonable
- Supports appear in the gcode preview
- Part sizes match the specified bounding box.
- Add the name and location of the gcode to the queue
- Add the cost and print time to the queue


- Gcode looks reasonable in Cura (see previous section)
- Build plate has a thin layer of glue
- Spool has enough fillament
- There are no jobs ahead of this print in the queue
- __Make a sticky note for the print__
	- Name of the person ordering the print
	- Name of the gcode file
	- Price of the print
	- Stick in on the printer
- __Mark it as "printing" in the queue__

**Comment by jejor** [comment]
@Flynnn does this issue still exist?
