### ISSUE TITLE
A406 Router Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#23]
- [ ] Clean up the existing SOP according to the style guide.
- [ ] Merge extra documents into the SOP, if appropriate. 
- [ ] Review/revise the existing SOP and documentation.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> Revisions for A406 PCB router:
> 
> -   Tool settings, "Tool Oracle"  needs to be cleaned up with more tools added.
> 
> -   More detail about how to choose tools when the tools are not all selected for the job
> 
> -   Update "ATC control panel"  - How to manually change out tools and add new ones.
> 
> -   Low Air Pressure"  warning - how to fix it.
> 
> -   "Get Tool" and "Return Tool."  - Depends on there being air pressure.
> 
> -   Add the "A406 Bits" image to the SOP.
> 
> -   "ATCH Control Panel" accessible by going to CnC mode
> 
> -   Machine must be out of "Emergency Stop" mode.
> 
> -   Machine will home and then check for tool heads.
> 
> -   If the machine spies a new tool in the spindle, it will list as "undefined," and you can define it from there.

**Comment by faberc** [comment]
Changes have been made. Unsure if this issue still exists. Needs testing with a non-technical person.

**Comment by jejor** [comment]
done
