### ISSUE TITLE
LPKF Router Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#24]
- [ ] Clean up the existing SOP according to the style guide.
- [ ] Merge extra documents into the SOP, if appropriate. 
- [ ] Review/revise the existing SOP and documentation.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by faberc** [comment]
Everything should be merged into one document. Issue still exists.

**Comment by jejor** [comment]
This issue has been merged with Issue #39
