### ISSUE TITLE
Shop Tool Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#26]
- [x] Scroll Saw SOP
    - [x] Get manufacturer manual, if possible.
- [x] Belt Grinder SOP
    - [x] Get manufacturer manual, if possible.
- [x] Arbor Press SOP
    - [x] Get manufacturer manual, if possible.
- [x] Bench Grinder SOP
    - [x] Get manufacturer manual, if possible.

**Comment by faberc** [comment]
Issue still exists.

**Comment by jejor** [comment]
sops done
