### ISSUE TITLE
Hand Tool Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#27]
- [x] Angle Grinder
    - [x] Write a short SOP on how to not be dumb with this tool.
    - [x] Get manufacturer manual, if possible.
- [x] Sawz-all
    - [x] Write a short SOP on how to not be dumb with this tool.
    - [x] Get manufacturer manual, if possible.
- [x] Hand Drill
    - [x] Write a short SOP on how to not be dumb with this tool.
    - [x] Get manufacturer manual, if possible.
- [x] Impact Driver
    - [x] Write a short SOP on how to not be dumb with this tool.
    - [x] Get manufacturer manual, if possible.

**Comment by jejor** [comment]
Saws-All pic is not loading. Do SOP's need to be written for the Shop and Hand Tools?

**Comment by Joedang** [comment]
Yes. I was planning to have a single "Here's how to avoid being stupid with shop/hand tools." document, since the individual documents would be pretty short, but maybe it's better to keep the "Everything has an SOP." convention.

As to why it looks like it isn't loading... The image isn't loading because it doesn't exist yet. The template that generates the list of machines takes an image location from `_data/machines.yml`, but that file gives no such location.

**Comment by faberc** [comment]
Confirmed issue still exists.

**Comment by jejor** [comment]
The angle grinder sop is pretty much done. I'm on the other side of the country right now so could someone else find the specific angle grinder manual/specs? Thank you!
