### ISSUE TITLE
Soldering Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#28]
- [ ] Merge extra documents, if appropriate. 
- [ ] Review/revise the existing documentation.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

We probably don't need an SOP for the soldering equipment.

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> We might want to mention some recommended working temperatures.

**Comment by haneefmubarak** [comment]
Also @Joedang wrt

> We probably don't need an SOP for the soldering equipment.

_what if someone doesn't know where the on and off buttons are?_

***clearly, an SOP is necessary*** /s

**Comment by haneefmubarak** [comment]
From the doc (migrating), regarding the Metcal (black) soldering machines:

> 1.  Turn on Fume Extractor (it sits on the floor in the middle of the two soldering desks), the power switch is on the back and lights up when on.
> 
> 2.  Turn on Metcal MX-5200 using the big red button on the top of the machine and make sure the LCD output says Ready.
> 
> 3.  Confirm which output you're using by pressing the button to the left of the LCD display; if you're using the right output, there will be a flashing white box on the right side of the display.
> 
> 4.  Tin the tip of the soldering iron by coating the tip in solder, then get to work.
> 
> 5.  Make sure the soldering iron is seated in its stand when not in use, never put it down on the workbench.
> 
> 6.  When you're done soldering, clean off the tip of the iron on the sponge/steel wool contained in its stand, re-tin the tip of the iron, and return the iron to its stand.
> 
> 7.  Turn off the Metcal.
> 
> 8.  Turn off the Fume Extractor.
> 
> 9.  Make to clean up your station and wash your hands when you're done.

**Comment by faberc** [comment]
Maybe get all of the Soldering documentation into one page.
