### ISSUE TITLE
VNA Documentation

### ISSUE THREAD

**Issue by Joedang** [psu-epl/psu-epl.github.com#30]
- [ ] Clean up the existing SOP according to the style guide.
- [ ] Review/revise the existing SOP and documentation. This will require input from @glennl. It may not even be necessary.
- [ ] Add any missing documentation (manufacturer manual, et cetera).

**Comment by Flynnn** [comment]
Assign Chris Maybe?

**Comment by Flynnn** [comment]
Assigning myself to this temporarily as an impetus to learn. My process will be to consult Glenn. However, I won't be able to dedicate the serious time that it deserves until probably very late in the game, so if someone wants to take it over from me, I invite that.

**Comment by faberc** [comment]
Confirmed issue still exists. Just needs cleaning up.

**Comment by Flynnn** [comment]
Absolutely impossible to make sense of without pictures.

Haneef:
"So imagine that I hadn't been trained on the VNA (twice!) by both Cam and Glenn - I would be so confused as to how to use this machine to accomplish what I want to do (or even what it was exactly that I wanted to do)."

This page needs more warnings.

**Comment by jejor** [comment]
This equipment is on a need to know basis. told to close.
