### ISSUE TITLE
Back up all images to Managers folder on Google Drive

### ISSUE THREAD

**Issue by Flynnn** [psu-epl/psu-epl.github.com#35]
Back up all images currently hosted on the website/github to the Managers Google Drive.

**Comment by Joedang** [comment]
So, this would naively copy every PNG and JPG file into a directory called `imgDump` with the same subdirectory structure, to avoid collisions. (Many of the images are just called "image1.png", since they were pasted directly into GH's editor.)

```bash
mkdir imgDump
find images doc \
	-type f \( -iname '*.jpg' -o -iname '*.png' \) \
	-exec cp -v --parents {} -t imgDump/ \;
```
