### ISSUE TITLE
LPKF SOP update items

### ISSUE THREAD

**Issue by armaanhammer** [psu-epl/psu-epl.github.com#39]
Needs to add instruction to click the camera icon in Select Head section of Processing screen to set absolute position for design placement. Failing to do this will result in the design being placed in an unexpected location.

Also add tool change tracking and returning.

Also add toolpath editing info.

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> During the generate toolpath process found the edit material setting and material thickness on SOP is in inches but program has it in mm putting both would be helpful even though it is already set right.
> Could not easily find where to set Isolation type not clear that it was under technology dialog and that shows insulate not isolate not clear if they are the same or different (talked to Chris he said it was a spelling mistake on the SOP)
> 
> Should add note that the routing type is the contour routing at bottom of the technology dialog box and that after clicking on the show details that the router bit changed in the tool section towards the top 
> 
> Should add note if you are supposed to close dialog box or click start on it to proceed and what to do when computation results pops up on screen and says that there is no source object for insulate or contour routing of drilling  and what to do if it says there is a missing required tool. (The errors were popping up because the fiducials were on the inside of the artwork make note that they should be on the outside.) [Errors had persisted even after having fiducials on the outside errors were also being caused by not having layers correct when importing files had accidently tried with txt files  from folder on circuit board training on the desktop]
> Under set up machine to cut in the category of edit pattern placement on the PCB blank it says to select mouse cursor mode it wasn’t where it says on the sop and I did find it but I don’t remember what I did to get to it I think I clicked on machining not machining view and saw it on a menu on the left hand side 
> During machining view artwork is not visible for me so I can not right click on the artwork and select placement I had to go to machining at the top to fin the option for placement and it is saying to do that for the center [This error was also likely from importing the files wrong]
> 
> Going back through again after putting fiducials on the outside of the drawing and using the settings on the SOP after clicking start on the Technology dialog box there is an error and 3 warnings pop up no instructions on what to do at this point. [ This error was also from importing files wrong Chris fixed this by reimporting the files right and after clicking start on the dialog box everything ran smoothly]
> 
> Make sure to unselect pockets on technology dialog

**Comment by haneefmubarak** [comment]
From the doc, per Gabby (migrating):

> Gabby’s notes:
> 
> - In the Add Fiducials section, we should say that you need to be in CAM view.
> - In the Generating Toolpath section:
> - Isolation Type should be changed to Insulation Type
> - Routing Type should be changed to Contour Routing
> - Under Set Up Machine to Cut, we should probably link to a page explaining how to add tools to the tool machine.

**Comment by haneefmubarak** [comment]
From the doc, per Chuck (migrating):

> Chuck faber adds:
> 
> "If you run into trouble assigning layers in a file gen, try editing the gerber file. Look for a line like %LNdefault*%. I’ve seen this string in gerbers generated by ADS, and it seems to force the LPKF software into assigning it to that named layer." ← Do we need this?

**Comment by haneefmubarak** [comment]
From the doc (migrating):

> More Notes:
> 
> In the SOP after placement of the board, at least on the new LPKF, a window like this will pop up:

**Comment by jejor** [comment]
Copied from issue #24 
..

- [ ] Clean up the existing SOP according to the style guide.
- [ ] Merge extra documents into the SOP, if appropriate. 
- [ ] Review/revise the existing SOP and documentation.
- [ ] Add any missing documentation (manufacturer manual, et cetera).
