### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by jejor** [psu-epl/psu-epl.github.com#41]
Images not loading on sponsors page! Slow to load page, pixelated/large images.

**Comment by Joedang** [comment]
Ugh, yeah. The page is [doc/policies/Sponsors.md](https://github.com/psu-epl/psu-epl.github.com/edit/master/doc/policies/Sponsors.md). 

TODO:
- [ ] find up-to-date logos for everything, with appropriate resolution
- [ ] copy those images to the repo
- [ ] replace external image links with links to the copied stuff
- [ ] display images at similar sizes
- [ ] fix markdown formatting (spaces after pound signs, random asterisks, exclamation points)

I can get this when I'm doing website fixes. Thanks for the issue. :)

**Comment by Joedang** [comment]
Okay, fixed with bfccd90.
