### ISSUE TITLE
ETL Page

### ISSUE THREAD

**Issue by jejor** [psu-epl/psu-epl.github.com#43]
doc/equip/testing/ETL 

- [ ] Needs booking pricing updated
- [ ] Needs booking email created and added
- [x] Need to change page to the same style as main equipment page: title, pics, link to sop, etc.
- [x] Need SOPs for all equipment started

**Comment by jejor** [comment]
SOPs Needed!
- [ ] Thermal Vacuum Chamber
- [ ] Thin-Film Depositor
- [ ] Helmholtz Cage
- [ ] Watlow Environmental Chamber
- [ ] BK Precision 8512 600W Programmable DC Electronic Load
- [ ] Keithley 228A Voltage/Current Source
- [ ] Heathkit ip-2718 Tri-power supply
- [ ] Keithley 6430 Sub-Femtoamp Remote sourcemeter
- [ ] Keithley 2182 nanovoltmeter
- [ ] Keithley 2400 SourceMeter
- [ ] Keithley 2420 3A Sourcemeter
- [ ] Atomic Force Mircoscope, qscope 250 quesant
- [ ] Blue M Stabil-therm Gravity Oven
- [ ] Hummer II Technics
- [ ] Olympus BHM Microscope
- [ ] Digital Ultrasonic Cleaner Isonic 2.1 Qt

**Comment by faberc** [comment]
Confirmed issue still exists.

**Comment by jejor** [comment]
@clarkatron  What is the status of the scanned documents? They are still on the bookshelf in the EPL.

**Comment by jejor** [comment]
New issues created, #98, #97, #96, #95, #94, #93, #92, #91, #90, #89, #88, #87, #81, #80. This issue is no longer needed to track ETL page.
