### ISSUE TITLE
QD-1390 Gauge Pressure "5psi"

### ISSUE THREAD

**Issue by MechBertrand** [psu-epl/psu-epl.github.com#45]
Two items:
The gauge on the regulator does not go low enough to determine when it is at 5psi. The first mark above zero is 10psi and 5 would be superimposed with the zero mark.

here's my experience:
0psi: I took over a cut after someone and the air compressor was turned off. flame resulted and the cut was not desirable.
5psi(adjusted to best approximation): Still a significant amount of smoke rising from the surface but being pushed away from the laser-head.
10psi: actually about the right amount.

Gauges are inaccurate at the extremes of their reading ranges.

I suggest upping the suggested value to 10psi(as adjusted by a manager with training on gauge decrements) **OR** swapping in a new gauge which can read low enough and testing until a proper value is achieved.

**Comment by faberc** [comment]
Fixed issue
