### ISSUE TITLE
Pick and Place Documentation

### ISSUE THREAD

**Issue by haneefmubarak** [psu-epl/psu-epl.github.com#49]
From the doc (migrating):

ISSUE: Please write Pick and Place Documentation

> All information can be found from through the homepage via the menu bar:
> https://www.liteplacer.com/
> 
> Link to Machine Assembly (Mechanical):
> https://www.liteplacer.com/the-machine/assembly-instructions/
> 
> Link to Electrical Assembly (Wiring):
> https://www.liteplacer.com/wiring/
> 
> Link to Setup and Calibration Instructions (Software):
> https://www.liteplacer.com/setup-and-calibration/
> 
> 
> To use without upward facing camera:
> On run job tab - select “Don’t use nozzle correction”
> 
> Contact information for the person who wrote the instructions if you have questsions: juha@liteplacer.com

**Comment by Flynnn** [comment]
Moved machine status log back to Google Drive. AFAIK we are only using github for issues regarding the documentation itself.

**Comment by faberc** [comment]
Pick and Place Documentation still yet to be done. Assigning Steven to this for now.

**Comment by jejor** [comment]
Still needs -set up for job section and test section
