### ISSUE TITLE
Update Manager Only Wiki

### ISSUE THREAD

**Issue by jejor** [psu-epl/psu-epl.github.com#53]
They haven't been updated in a while. Someone needs to go through them, probably @clarkatron first to assign tasks.

**Comment by Joedang** [comment]
The wiki for this site/repo was what all the documentation (per se) came from on the current site. I removed all the pages from it to avoid confusion. (A lot of it was incorrect and/or out of date.) But yes, someone should scrub through the manager-only wiki and update it.

**Comment by Joedang** [comment]
Brain fart: the documentation on the *current site* came from this repo's wiki.
