### ISSUE TITLE
Create material and printer selection guide

### ISSUE THREAD

**Issue by jvinh890** [psu-epl/psu-epl.github.com#60]
We need to have a page describing basic material properties between different printers and their materials, and how to choose between them.

Additionally, there's a reference to this guide on the site in the "before you start" section at the following URL. http://psu-epl.github.io/doc/equip/printer/3D-Printing-Checklist

**Comment by Flynnn** [comment]
When closing this issue, please make sure to follow suggestions in #67  by adding a link to the reference at http://psu-epl.github.io/doc/equip/printer/3D-Printing-Checklist.

"For material, type, and price please refer to: LINK HERE"

Replace LINK HERE with link to the new guide

**Comment by Flynnn** [comment]
Added a page for the guide. Linked to guide appropriately. Did not fill in information.
