### ISSUE TITLE
Integrate these notes into Form Labs SOP

### ISSUE THREAD

**Issue by Flynnn** [psu-epl/psu-epl.github.com#61]
These Form-Labs-Specific notes were on the 3D printing checklist. Integrate them into the form labs SOP:

# Using the Formlabs 2

## Generating Print Files
- There are no large horizontal surfaces
- There are no large-point supports in critical areas of the part
- PreForm says the item is printable (bottom right)
- Comment in the "manager's notes" field when you send it to the printer's queue
- Add the cost and print time to the queue
- __Make a sticky note for the print__
	- Name of the person ordering the print
	- Name of the STL files
	- Price of the print
	- Stick in on the _side_ printer

## Starting a Print
- Build plate is empty and clean (thing on top) 
- Tank vent is open (giant shampoo bottle thing in back)
- __Mark as "printing" in the queue__
- Move the sticky note to the _front_ of the printer
	- If there's no sticky note, make one! (see previous section)

## Removing a Print
- Soak the print in the left alcohol bath
	- Start a timer on your phone for 30 minutes
	- Move the sticky note to the bath
	- Indicating on the sticky note when you started the soak 
	- Swirl the alcohol bath
- Soak again in the right bath
- Wash the part
- Remove the support material (bend and pry with palms)
- UV cure the part
	- Start a timer (30 to 60 min)
	- Move the sticky to the UV oven
	- Note the start time
- __Mark the print as "Finished" in the queue__

**Comment by Flynnn** [comment]
`# Using the Formlabs 2

## Generating Print Files
- There are no large horizontal surfaces
- There are no large-point supports in critical areas of the part
- PreForm says the item is printable (bottom right)
- Comment in the "manager's notes" field when you send it to the printer's queue
- Add the cost and print time to the queue
- __Make a sticky note for the print__
	- Name of the person ordering the print
	- Name of the STL files
	- Price of the print
	- Stick in on the _side_ printer

## Starting a Print
- Build plate is empty and clean (thing on top) 
- Tank vent is open (giant shampoo bottle thing in back)
- __Mark as "printing" in the queue__
- Move the sticky note to the _front_ of the printer
	- If there's no sticky note, make one! (see previous section)

## Removing a Print
- Soak the print in the left alcohol bath
	- Start a timer on your phone for 30 minutes
	- Move the sticky note to the bath
	- Indicating on the sticky note when you started the soak 
	- Swirl the alcohol bath
- Soak again in the right bath
- Wash the part
- Remove the support material (bend and pry with palms)
- UV cure the part
	- Start a timer (30 to 60 min)
	- Move the sticky to the UV oven
	- Note the start time
- __Mark the print as "Finished" in the queue__`

**Comment by brandr2** [comment]
Most of the notes have been moved. Someone should try to add pictures of the build plate, tank vent, and alcohol baths if I don't get to it today.
