### ISSUE TITLE
K-40 Laser Cutter Issues

### ISSUE THREAD

**Issue by davidalay** [psu-epl/psu-epl.github.com#66]
Exporting Eagle
- cream-dxf.ulp does not download a .ulp file, it only links to a new tab displaying the code

Part 3
- Do we have a specific backing board we use or is it a piece of scrap wood?  We don't specify in the SOP
- Update pictures of chiller/fume vacuum to reflect new positions in the show.

**Comment by Flynnn** [comment]
We used to have a specific backing board. Someone stole it.

Corrected the language to refer to a non-specific board.
