### ISSUE TITLE
Titles are Inconsistent 

### ISSUE THREAD

**Issue by sharkyb** [psu-epl/psu-epl.github.com#68]
On [3D Printing Guide](http://psu-epl.github.io/doc/equip/printer/3D-Printing-Checklist) the titles have no consistent format with what is capitalized and not capitalized. 

Note: Capitalize the first word of the title, the last word of the title, and all nouns, pronouns, verbs, adverbs, adjectives, subordinating conjunctions, and a few conjunctions.

**Comment by Flynnn** [comment]
Good catch
