### ISSUE TITLE
Create issues for the following empty pages

### ISSUE THREAD

**Issue by Flynnn** [psu-epl/psu-epl.github.com#85]
I have to step away from github. Can the next person working on github create separate issues for the following:

"Write X SOP" where X is one of the following for each issue:

    Thermal Vacuum Chamber
    Thin Film Depositor
    Watlow Environmental Chamber
    Atomic Force Microscope (almost empty)
    Gravity Oven
    Sputtering System
    BHM Microscope
    Ultrasonic Cleaner
    Programmable DC Load
    Voltage/Current Source
    Power Supply
    Sourcemeters + Nanovoltmeter
    Lathe
    Drill Press (almost empty)

Note on each issue that the pages already exist, but are empty. Link to the empty pages.

**Comment by tylerhull** [comment]
Created all the pages for these!
