### ISSUE TITLE
Write SOP for Thermal Vacuum Chamber

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#87]
The page exists and needs an SOP written.

https://github.com/psu-epl/psu-epl.github.com/tree/master/doc/equip/testing/ETL/thermal-vacuum

**Comment by jejor** [comment]
Parker and/or Glenn should have access to most of this info. If not, someone will need to contact Erik Sanchez (esanchez@pdx.edu) since he was the original 'owner' for more information.

**Comment by jejor** [comment]
no documentation exists. contact glenn glennl@pdx.edu
