### ISSUE TITLE
Write SOP for Atomic Force Microscope

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#90]
Apparently this SOP is almost empty and needs to be more detailed.

https://github.com/psu-epl/psu-epl.github.com/tree/master/doc/equip/testing/ETL/atomic-force-microscope

**Comment by jejor** [comment]
I believe the paperwork and program (CD) for this is on the black bookshelf in the EPL (next to the desk).

**Comment by jejor** [comment]
I have emailed kt.training@kla-tencor.com and Gss.globalcontactcenter@kla.com for an operators manual since the original manufacturer Quesant was bought by Ambios Tech which is currently owned by KLA.

**Comment by jejor** [comment]
Response from kla: "Unfortunately, this was part of an acquisition. We discontinued this approximately 8 years ago and no longer provide support.
We will not be able to support this request."

**Comment by jejor** [comment]
However, the internet is a fantastic place. A Russian professor/mountaineer kept a copy of the Ambios Tech operators manual on his blog site. I have uploaded it to the Q250 folder.

**Comment by jejor** [comment]
I started working on this SOP, I'll finish it soon-ish

**Comment by jejor** [comment]
This machine was donated to chemistry department. for questions about use contact...


Marilyn Rampersad Mackiewicz, Ph.D.
Research Assistant Professor
She / Her / Hers | What is this?
Portland State University
Department of Chemistry
1719 SW 10th Ave,
Portland OR 97201
Science Building 1, Rm 538
Tel: 503-725-2360
Website: Laboratory of Nanostructured Materials
