### ISSUE TITLE
Add images to Sputtering System (Hummer II) SOP

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#92]
The page exists and needs an SOP written.

https://github.com/psu-epl/psu-epl.github.com/blob/d093473d8e3884bf7cc521277dc8be9beb156687/doc/equip/testing/ETL/hummer2/index.md

**Comment by jejor** [comment]
I believe the paperwork for this is on the black bookshelf in the EPL (next to the desk).

**Comment by jejor** [comment]
[ML003750045.pdf](https://github.com/psu-epl/psu-epl.github.com/files/3433727/ML003750045.pdf)

**Comment by jejor** [comment]
this sop is done. it needs to be reviewed and images need to be added

**Comment by jejor** [comment]
just needs a review and images, merged with sop review issue
