### ISSUE TITLE
Write SOP for BHM Microscope

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#93]
Page exists, needs sop written.

https://github.com/psu-epl/psu-epl.github.com/tree/d093473d8e3884bf7cc521277dc8be9beb156687/doc/equip/testing/ETL/bhm-microscope

**Comment by jejor** [comment]
I believe the paperwork and program (CD) for the microscope are on the black bookshelf in the EPL (next to the desk).

**Comment by jejor** [comment]
finished today. feel free to review it. 

it would be good to have someone (in person) run through the sop and make notes.
