### ISSUE TITLE
Write SOP for the Ultrasonic Cleaner

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#94]
Page exists, needs SOP written.

https://github.com/psu-epl/psu-epl.github.com/tree/d093473d8e3884bf7cc521277dc8be9beb156687/doc/equip/testing/ETL/isonic-cleaner

**Comment by jejor** [comment]
We don't have any current info on this piece of equipment. I sent an email to info@isonicinc.com for an official manual. I'll attach it if they send one.

**Comment by jejor** [comment]
manual shared: https://drive.google.com/file/d/1CanijB_iM83pFrIxmtNyhZdjI6WlzMVN/view
also uploaded to respective folder! WOO

**Comment by jejor** [comment]
needs images, references in review issue
