### ISSUE TITLE
Write SOP for the Programmable DC Load (BK8512)

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#95]
Page exists, needs SOP.

https://github.com/psu-epl/psu-epl.github.com/tree/a3c961c237833bc0010bf8bb7114e640580abc34/doc/equip/testing/ETL/BK8512

**Comment by jejor** [comment]
I've uploaded the manual and datasheet for this into it's respective folder.
The manual is super helpful.

**Comment by jejor** [comment]
sop is done, needs review. merged with sop review issue
