### ISSUE TITLE
Write SOP for Voltage/Current source (keithly 6430)

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#96]
Page exists, needs SOP written.

https://github.com/psu-epl/psu-epl.github.com/tree/96871d31e86f171ea7600604522907436b551909/doc/equip/testing/ETL/keithley6430

**Comment by jejor** [comment]
Please refer to the Keithley Instruction Manual and Product Overview booklet in the EPL on the bookshelf. @clarkatron needs to scan these books

this piece of equipment uses the labtracer software: https://www.tek.com/source-measure-units/2400-software/labtracer-29-unsupported

Notes:
[ ] - make pdf of instruction manual
[ ] - make pdf of product overview booklet
[ ] - set up computer to run the labtracer software (*Does not work with Windows 7 or newer*)
[ ] - write up sop for using the software and the sourcemeter

**Comment by jejor** [comment]
I found a pdf manual for this, uploaded to respective folder

**Comment by jejor** [comment]
sop is done, needs a few pictures added. merged with sop review issue
