### ISSUE TITLE
Write SOP for Lathe

### ISSUE THREAD

**Issue by tylerhull** [psu-epl/psu-epl.github.com#99]
Page exists, SOP needs written or updated.

https://github.com/psu-epl/psu-epl.github.com/tree/7b9eab448340560929b434ce497781cc12e36426/doc/equip/machining/lathe

**Comment by brandr2** [comment]
https://github.com/psu-epl/psu-epl.github.com/blob/master/doc/equip/machining/lathe/In-progress%20SOP

I started working on this today, there are a couple of sections left to fill out and I need to add pics.

**Comment by Joedang** [comment]
I took a bunch of pictures before I left. I'll try to remember to upload
them tonight.
